### ISSUE TITLE
Make static assets from the extension repos available

### ISSUE THREAD

**Issue by micbar** [owncloud/owncloud.github.io#14]
## Add Static assets

Sometimes, ocis extensions need to add static assets.

### Example
https://github.com/owncloud/ocis/pull/431

@xoxys This collides with your `git-batch` script.

We would need to find a convention how to do that. Open for suggestions.

**Comment by xoxys** [comment]
@micbar does this issue still exist? Can you explain a bit more whats needed?

**Comment by micbar** [comment]
it was fixed. Thanks.
