### ISSUE TITLE
Add class images on right side

### ISSUE THREAD

**Issue by felixboehm** [owncloud/owncloud.github.io#18]
needs custom css like

``` 
figure.floatright {
	max-width: 30%;
	width: auto\9*0.3; /* ie8 */
	height: auto;
	float: right;
}
```

use like

```
{{< figure class="floatright" src="/media/is.png" width="100%" height="auto" >}}
```

<img width="1243" alt="nice image on right side" src="https://user-images.githubusercontent.com/1204907/94931628-44d96400-04c8-11eb-825a-dd24e96f0c02.png">

**Comment by xoxys** [comment]
You should use flexboxes these days

**Comment by xoxys** [comment]
Forget what I said, doesnt work well for images
