### ISSUE TITLE
add backlink to source page

### ISSUE THREAD

**Issue by butonic** [owncloud/owncloud.github.io#2]
eg https://owncloud.github.io/extensions/ocis_reva/users/ should have a link to https://github.com/owncloud/ocis-reva/blob/master/docs/users.md

maybe call it 'edit on github'

**Comment by butonic** [comment]
cc @xoxys

**Comment by xoxys** [comment]
@butonic Possible but need configuration per page front matter. I don't see any chance to set this globally or even per extension...

```
---
title: "Users"
date: 2020-01-16T00:00:00+00:00
anchor: "users"
weight: 35
geekdocRepo: https://github.com/owncloud/ocis-reva
geekdocEditPath: edit/master/docs
geekdocFilePath: users.md
---

```

Result: 
![grafik](https://user-images.githubusercontent.com/3391958/75266468-aaf35f80-57f2-11ea-8ad4-2b85b1181a87.png)

**Comment by xoxys** [comment]
btw. `anchor: ` in the front matter has afaik no effect with this theme and can simply be dropped

**Comment by micbar** [comment]
added to https://github.com/owncloud/boilr-ocis-extension
