### ISSUE TITLE
fold the left side navigation as it it getting too long 

### ISSUE THREAD

**Issue by felixboehm** [owncloud/owncloud.github.io#20]
Keep level 1 (orange) and level 2 and hide all subitems by default.

Example:
Clicking on "Development" should navigate to https://owncloud.github.io/ocis/development/
And unfold the navigation to show its submenu items
- Getting Started with Development
- Build ocis
- Testing
- Debugging
- Tracing
- Build the documentation

**Comment by xoxys** [comment]
As I also wanted to have this feature in the theme for a long time... I have added it now. See https://github.com/thegeeklab/hugo-geekdoc/pull/23. If you consider updating, keep in mind that you are multiple versions behind and there might be breaking changes.
