### ISSUE TITLE
make headings have an accessible anchor 

### ISSUE THREAD

**Issue by butonic** [owncloud/owncloud.github.io#3]
so we can link to headings like with the one below
# [⛓](#level-1) Level 1 
### [⛓](#level-3) Level 3

edit: ... well sort of ...

**Comment by xoxys** [comment]
Anchors are already available e.g. https://owncloud.github.io/extensions/ocis_reva/users/#json-driver. I know it would be cool to have a link you can easily copy. But it's not that easy with hugo and even harder if you want to avoid JavaScript as much as possible...

**Comment by xoxys** [comment]
https://github.com/gohugoio/gohugoioTheme/blob/9d6c945dcb655c2b6295c0f5fad23a92b0a9e5f3/assets/js/anchorforid.js

That's how the gohugo theme solved it. I'll have a look later

**Comment by xoxys** [comment]
Fixed by https://github.com/owncloud/owncloud.github.io/pull/4 @butonic please review
